import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { invoke } from "@tauri-apps/api/core";
import "./styles.css";
import "./diagnostics_panel";

type SemanticEvent = { id: string; raw_event_id: string; timestamp_ns: number; app_name?: string; window_title?: string; category: string; summary: string; confidence: number; model_name: string; created_at: string };
type CaptureSettings = { enabled: boolean; mouse_enabled: boolean; keyboard_enabled: boolean; excluded_applications: string[]; watched_folders: string[] };
type QueueStatus = { pending: number; processing: number; complete: number; failed: number; cancelled: number };

async function loadInsights(query?: string) { try { return await invoke<SemanticEvent[]>("list_semantic_events", { limit: 100, query: query || null }); } catch { return []; } }

function App() {
  const [insights, setInsights] = useState<SemanticEvent[]>([]), [query, setQuery] = useState(""), [section, setSection] = useState<"timeline" | "search" | "settings">("timeline"), [settings, setSettings] = useState<CaptureSettings | null>(null), [queue, setQueue] = useState<QueueStatus>({ pending: 0, processing: 0, complete: 0, failed: 0, cancelled: 0 });
  const refresh = () => loadInsights(section === "search" ? query : undefined).then(setInsights);
  useEffect(() => { refresh(); invoke<CaptureSettings>("get_capture_settings").then(setSettings).catch(() => undefined); invoke<QueueStatus>("processing_queue_status").then(setQueue).catch(() => undefined); }, []);
  useEffect(() => { if (section === "search") refresh(); }, [query, section]);
  const toggleCapture = async (enabled: boolean) => { await invoke(enabled ? "start_capture" : "stop_capture"); setSettings((current) => current ? { ...current, enabled } : current); };
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">C</span><span>Chronicle</span></div><nav aria-label="Primary navigation"><button className={`nav-item ${section === "timeline" ? "active" : ""}`} onClick={() => setSection("timeline")}>Timeline</button><button className={`nav-item ${section === "search" ? "active" : ""}`} onClick={() => setSection("search")}>Search</button><button className={`nav-item ${section === "settings" ? "active" : ""}`} onClick={() => setSection("settings")}>Settings</button></nav><div className="capture-card"><div className={`status-dot ${settings?.enabled ? "on" : ""}`} /><div><strong>{settings?.enabled ? "Capture enabled" : "Capture is off"}</strong><span>{queue.pending} processing tasks pending.</span></div></div></aside><section className="content"><header className="topbar"><div><p className="eyebrow">LOCAL MEMORY ENGINE</p><h1>{section[0].toUpperCase() + section.slice(1)}</h1></div><button className="quiet-button" onClick={refresh}>Refresh</button></header>{section === "settings" ? <section className="settings-panel"><h2>Permissions and privacy</h2><p className="muted">Raw capture is private and never appears in the activity feed. Only processed local-model insights are shown.</p>{settings && <label className="setting-row"><span><strong>Foreground application tracking</strong><small>Captures source evidence for local processing.</small></span><input type="checkbox" checked={settings.enabled} onChange={(event) => toggleCapture(event.target.checked)} /></label>}</section> : <><div className="hero"><div><p className="eyebrow">TODAY</p><h2>Your computer, remembered.</h2><p className="muted">Interpreted activity appears here after local processing. Raw evidence stays private.</p></div><div className="metric"><span>Insights ready</span><strong>{insights.length}</strong></div></div>{section === "search" && <input className="search-input" placeholder="Search processed activity…" value={query} onChange={(event) => setQuery(event.target.value)} />}<section className="timeline"><div className="section-heading"><h3>{section === "search" ? "Processed results" : "Recent insights"}</h3><span className="muted">LLM processed</span></div>{insights.length ? insights.map((event) => <article className="event-row" key={event.id}><time>{new Date(event.timestamp_ns / 1_000_000).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time><div className="event-icon">•</div><div className="event-body"><div className="event-top"><strong>{event.app_name || "Unknown application"}</strong><span className="event-status">{Math.round(event.confidence * 100)}% confidence</span></div><p>{event.summary}</p><span className="event-type">{event.category} · {event.model_name}</span></div></article>) : <p className="muted empty">No processed insights yet.</p>}</section></>}</section></main>;
}

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
